"use strict";
exports.__esModule = true;
var graphql_compose_1 = require("graphql-compose");
var mutationFields = require("./mutations");
var queryFields = require("./queries");
require("./relations");
graphql_compose_1.schemaComposer.Query.addFields(queryFields);
graphql_compose_1.schemaComposer.Mutation.addFields(mutationFields);
var schema = graphql_compose_1.schemaComposer.buildSchema();
exports["default"] = schema;
